### ISSUE TITLE
nginx cookbook is outdated

### ISSUE THREAD

**Issue by tvb** [vkhatri/chef-thumbor-ng#25]
```
    amazon-ebs:
    amazon-ebs: ================================================================================
    amazon-ebs: Recipe Compile Error in /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/thumbor_ng/recipes/default.rb
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: NoMethodError
    amazon-ebs: -------------
    amazon-ebs: undefined method `[]' for nil:NilClass
    amazon-ebs:
    amazon-ebs: Cookbook Trace:
    amazon-ebs: ---------------
    amazon-ebs: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/nginx/recipes/ohai_plugin.rb:27:in `from_file'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/nginx/recipes/default.rb:21:in `from_file'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/thumbor_ng/recipes/nginx.rb:20:in `from_file'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/thumbor_ng/recipes/default.rb:32:in `from_file'
    amazon-ebs:
    amazon-ebs: Relevant File Content:
    amazon-ebs: ----------------------
    amazon-ebs: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/nginx/recipes/ohai_plugin.rb:
    amazon-ebs:
    amazon-ebs:  20:  #
    amazon-ebs:  21:
    amazon-ebs:  22:  ohai "reload_nginx" do
    amazon-ebs:  23:    action :nothing
    amazon-ebs:  24:    plugin "nginx"
    amazon-ebs:  25:  end
    amazon-ebs:  26:
    amazon-ebs:  27>> template "#{node['ohai']['plugin_path']}/nginx.rb" do
    amazon-ebs:  28:    source "plugins/nginx.rb.erb"
    amazon-ebs:  29:    owner "root"
    amazon-ebs:  30:    group "root"
    amazon-ebs:  31:    mode 00755
    amazon-ebs:  32:    variables(
    amazon-ebs:  33:      :nginx_prefix => node['nginx']['source']['prefix'],
    amazon-ebs:  34:      :nginx_bin => node['nginx']['binary']
    amazon-ebs:  35:    )
    amazon-ebs:  36:    notifies :reload, 'ohai[reload_nginx]', :immediately
```

Perhaps use `chef_nginx` instead?

**Comment by vkhatri** [comment]
@tvb Sorry for the delay. I will take a look.
